// sidebars.js
module.exports = {
  // By default, Docusaurus will generate a sidebar from the docs folder structure.
  // Here we define a custom order that is easy to scale.
  tutorialSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started", // docs/getting-started.md
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/intro", // docs/tutorials/intro.md
      ],
    },
    {
      type: "category",
      label: "API Reference",
      items: [
        // Example placeholders — add real doc files under docs/api/
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },
    {
      type: "category",
      label: "Examples",
      items: [
        // Add examples here
        {
          type: "autogenerated",
          dirName: "examples",
        },
      ],
    },
  ],
};
